; =============================================================================
; KIZUNA MSXLIB - as 16 cores da paleta padrao do MSX (TMS9918 / V9938)
; =============================================================================
COLOR_TRANSPARENT EQU 0
COLOR_BLACK       EQU 1
COLOR_MEDIUM_GREEN EQU 2
COLOR_LIGHT_GREEN EQU 3
COLOR_DARK_BLUE   EQU 4
COLOR_LIGHT_BLUE  EQU 5
COLOR_DARK_RED    EQU 6
COLOR_CYAN        EQU 7
COLOR_MEDIUM_RED  EQU 8
COLOR_LIGHT_RED   EQU 9
COLOR_DARK_YELLOW EQU 10
COLOR_LIGHT_YELLOW EQU 11
COLOR_DARK_GREEN  EQU 12
COLOR_MAGENTA     EQU 13
COLOR_GRAY        EQU 14
COLOR_WHITE       EQU 15
